name: Saludo Cada 10 Minutos

on:
  schedule:
    # Esta expresión cron se ejecuta cada 10 minutos.
    # El formato es: minuto hora día-del-mes mes día-de-la-semana
    # */10 en la posición de minuto significa "cada 10 minutos".
    - cron: '*/10 * * * *'

jobs:
  decir_hola:
    runs-on: ubuntu-latest
    
    steps:
      - name: Mostrar el saludo "HOLA"
        run: echo "HOLA"
